// const express=require("express")
// const userRouter = require("./routes/user.router")
// const app=express()
// app.use(express.json({limit:"16kb"}))
// app.use(express.urlencoded({extended:true,limit:"16kb"}))
// app.use(express.static("public"))
// app.use("/api/v1/users",userRouter)
